# Generated by Django 5.0.2 on 2024-04-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('magico', 'Mágico'), ('fisico', 'Físico')], max_length=50)),
                ('quantidade_especializacoes', models.IntegerField()),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('raca', models.CharField(choices=[('humano', 'Humano'), ('elfo', 'Elfo'), ('anao', 'Anão'), ('qunari', 'Qunari')], max_length=50)),
                ('rank', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalhesPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('nivel_recomendado', models.IntegerField(default=1)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquisitor.classe')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquisitor.personagem')),
            ],
        ),
    ]
