# Generated by Django 5.0.2 on 2024-04-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquisitor', '0002_remove_detalhespersonagem_nivel_recomendado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalhespersonagem',
            old_name='tipo',
            new_name='classe',
        ),
    ]
