# Generated by Django 5.0.2 on 2024-04-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquisitor', '0003_rename_tipo_detalhespersonagem_classe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalhesPersonagem',
            new_name='ReferenciasPersonagem',
        ),
    ]
