# Generated by Django 5.0.2 on 2024-04-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquisitor', '0004_rename_detalhespersonagem_referenciaspersonagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenciaspersonagem',
            options={'verbose_name': 'referencia personagem', 'verbose_name_plural': 'referencias personagens'},
        ),
    ]
