# Generated by Django 5.0.2 on 2024-04-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquisitor', '0005_alter_referenciaspersonagem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenciaspersonagem',
            options={'verbose_name': 'referencia do personagem', 'verbose_name_plural': 'referencias dos personagens'},
        ),
    ]
