# Generated by Django 5.0.2 on 2024-04-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquisitor', '0006_alter_referenciaspersonagem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personagem',
            options={'verbose_name_plural': 'personagens'},
        ),
    ]
