# Generated by Django 5.0.2 on 2024-04-19 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquisitor', '0008_classe_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='rank',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
